Feature/[P2022-1131] board view
intive/patronage22-bialystok-js-simple-jira pull request #63
Opened 2022-02-25 09:20 UTC by Voland91

2022-02-25 16:19 UTC, KarolCiesluk requested changes

2022-02-25 16:19 UTC, KarolCiesluk commented on src/views/Projects/Projects.style.tsx
> +  height: calc(100vh - 80px);
In my opinion it's risky to set height this way. Imagine you have a lot of projects on the page. Potencially your `background-color` will end at some point. I would at least use `min-height` insted of `height` here.

2022-02-25 16:19 UTC, KarolCiesluk commented on src/views/Board/Board.tsx
> +    </StyledPageWrapper>
I don't know If you are responsible for that in this task but notice that on figma text of `NavBar` and `PageHeader` aligns vertically with `TaskCards` so probably the same wrapper should be used in all three components.

2022-02-28 20:02 UTC, Voland91 commented on src/components/ProjectCard/styled.tsx
> +  cursor: "pointer",
Good point, fixed

2022-02-28 20:02 UTC, Voland91 commented on src/components/PageHeader/PageHeader.tsx
>            <StyledButton onClick={buttonHandler}>{buttonText}</StyledButton>
good point too, fixed

2022-02-28 20:02 UTC, Voland91 commented on src/components/PageHeader/PageHeader.tsx
> +              <SubTitle>{"Return to Projects"}</SubTitle>
another good point :) fixed

2022-02-28 20:04 UTC, Voland91 commented on src/views/Projects/Projects.style.tsx
> +  height: calc(100vh - 80px);
bgc fixed, there may be some problems with mobile but on desktop it's ok

2022-02-28 20:05 UTC, Voland91 commented on src/views/Board/Board.tsx
> +    </StyledPageWrapper>
Navbar is on higher component

2022-03-01 07:50 UTC, KarolCiesluk approved these changes
:tada:

2022-03-01 07:50 UTC, KarolCiesluk commented on src/views/Projects/Projects.style.tsx
> +  height: calc(100vh - 80px);
Yes, It can be a problem with moblile but It's for both `height` and `min-height`. I think the most predictable way would be to set `background-color` in some sort of global styles f.ex. on `body` or `html` tags.

2022-03-01 19:29 UTC, merged