P2022 215 routing rebuilding
intive/patronage22-bialystok-js-simple-jira pull request #9
Opened 2022-01-20 19:04 UTC by jprymak

2022-01-21 10:58 UTC, konradkierus requested changes

2022-01-21 10:58 UTC, konradkierus commented on src/links/links.ts
> +interface objectType {
interfaces should start with capital letter

2022-01-21 10:58 UTC, konradkierus commented on src/links/links.ts
> +export const links: objectType[] = [
please convert to enum, e.g.
```
enum Pages {
  Home: '/',
  Secondary: '/second'
}
```

2022-01-21 10:59 UTC, konradkierus commented
Please also use [P2022-215] PR naming convention when you put ticket number in PR title.

2022-01-22 10:06 UTC, jprymak commented on src/links/links.ts
> +interface objectType {
thanks :)

2022-01-22 10:06 UTC, jprymak commented on src/links/links.ts
> +export const links: objectType[] = [
i suppose when defining enums assignment operators should be used instead of ":"

2022-01-24 10:38 UTC, konradkierus commented on src/links/links.ts
> +export const links: objectType[] = [
@jprymak yes, sorry, I mixed the syntax when I was writing my comment :)

2022-01-25 07:22 UTC, konradkierus approved these changes

2022-01-25 19:39 UTC, merged