[P2022-1723] add routing to issue details
intive/patronage22-bialystok-js-simple-jira pull request #95
Opened 2022-03-19 22:15 UTC by jprymak

[https://tracker.intive.com/jira/secure/RapidBoard.jspa?rapidView=1485&view=detail&selectedIssue=P2022-1723&sprint=4957](https://tracker.intive.com/jira/secure/RapidBoard.jspa?rapidView=1485&view=detail&selectedIssue=P2022-1723&sprint=4957)

- removed temporary issue component
- added routing to issue details
- added temporary ticket to each board column for incoming issue api integration purposes

2022-03-21 18:54 UTC, Voland91 commented on src/mockData/mockBoardStatus.tsx
> +  { boardId: 3, statusId: 3, status: { code: "done", id: 3 } },
I thinkt it should look like data from API, there is no boardId and statusId

2022-03-21 18:55 UTC, Voland91 commented on src/api/requestsApi.ts
> -      return [, status.data];
I need this status.data as a second parameter to correctly add new column

2022-03-21 18:55 UTC, Voland91 commented on src/api/requestsApi.ts
> -      return [filteredStatus, status.data];
Same situation like in line 30

2022-03-23 20:34 UTC, jprymak commented on src/api/requestsApi.ts
> -      return [filteredStatus, status.data];
I am a little but confused on this one :)

2022-03-23 20:35 UTC, jprymak commented on src/mockData/mockBoardStatus.tsx
> +  { boardId: 3, statusId: 3, status: { code: "done", id: 3 } },
I've changed the code resemble data returned from api

2022-03-24 20:13 UTC, Voland91 requested changes

2022-03-24 20:15 UTC, jprymak commented on src/App.tsx
> +            path='projects/:projectName&:projectId/:board/:issue&:issueId'
done

2022-03-24 20:15 UTC, jprymak commented on src/api/requestsApi.ts
> -      return [, status.data];
done

2022-03-24 20:24 UTC, merged